export const ADD_TO_CART = "ADD_TO_CART";
// export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
// export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
export const REMOVE_TO_CART = 'REMOVE_TO_CART';
// export const REMOVE_TO_CART_SUCCESS = 'REMOVE_TO_CART_SUCCESS';
// export const REMOVE_TO_CART_FAILURE = 'REMOVE_TO_CART_FAILURE';
